server:
  port: 80

spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/magazine
      username: magazine
      password: 0852
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL92Dialect
#          show_sql: true
      hibernate:
        ddl-auto: update


jwt:
  token:
    secret: idgoup_donik
    validity: 21600000
